# ===============================
# DATASOURCE (PROD)
# ===============================
spring.datasource.url=jdbc:postgresql://<PROD_DB_HOST>:5432/pdf_manager
spring.datasource.username=<PROD_DB_USER>
spring.datasource.password=<PROD_DB_PASSWORD>

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# LOGGING
# ===============================
logging.level.root=INFO
logging.level.edu.usip.pdfdocumentmanager=INFO

# ===============================
# STORAGE
# ===============================
# Si en prod sigues usando filesystem local
file.storage.path=/var/app/uploads

# ===============================
# AWS (solo si más adelante usas S3)
# ===============================
aws.region=us-east-1
# aws.s3.bucket=mi-bucket-prod
