package edu.usip.pdfdocumentmanager.telegram;

public enum BotState {
    IDLE,
    CHATPDF_CHATTING,

    // Upload PDF
    ADMIN_WAITING_PDF,
    ADMIN_WAITING_TITLE,
    ADMIN_WAITING_AUTHOR,
    ADMIN_WAITING_DEGREE,
    ADMIN_WAITING_DEFENSE_DATE,

    // Search
    WAITING_SEARCH_QUERY,
    SEARCH_PREV,
    SEARCH_NEXT,
    SEARCH_NEW,
    SEARCH_BROWSING,
    BACK_MAIN,

    // Users
    ADMIN_WAITING_NEWUSER_NAME,
    ADMIN_WAITING_NEWUSER_PHONE,
    ADMIN_WAITING_NEWUSER_ROLE,
    ADMIN_WAITING_DISABLE_PHONE
}
